# Generated by Django 4.1.7 on 2023-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date logined")),
            ],
        ),
    ]
