# Generated by Django 4.1.7 on 2023-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ship", "0002_remove_operator_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_name", models.CharField(max_length=200)),
            ],
        ),
    ]
